[package]
description = "cita protocol"
name = "libcitaprotocol"
version = "2.0.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
protobuf = { version = "2.0.4", features = ["with-bytes"]}
